project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Machine Learning and Artificial Intelligence for Advanced Therapeutic Technologies"
  author: "Danilo Augusto Sarti"
  date: "2025-10-21"
  site-url: "https://danilosarti.github.io/att_ml_ai_book"
  chapters:
    - index.qmd
    - introduction_AI.qmd
    - supervised_regression.qmd
    - three_methods.qmd
    - neural_networks.qmd
    - introd_bayesian.qmd
    - intro_missing.qmd
    - high_dims.qmd
    - clustering.qmd
    - interpretable.qmd
    - genai_foundations.qmd
    - genai_app.qmd
    - references.qmd

bibliography:
  - references.bib
cite-method: citeproc
link-citations: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    mermaid-format: png
  epub: default
