project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Machine Learning and AI for Health Sciences"
  author: "Danilo Augusto Sarti"
  date: "2025-10-21"
  site-url: "https://danilosarti.github.io/att_ml_ai_book"
  chapters:
    - index.qmd
    - introduction_AI.qmd
    - references.qmd

bibliography:
  - references.bib
cite-method: citeproc
link-citations: true

format:
  html:
    theme:
      - cosmo
      - brand
  
